language: python
python:
 - "3.6"
install:
 - pip install -r requirements.txt
 - pip install -r tests/requirements.txt
 - pip install codecov
script:
 - python3 -m pytest --cov-report xml --cov=app --cov=poll --cov=formatters --cov=mattermost_api
after_success:
 - codecov
