name: pytest

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r tests/requirements.txt
        pip install codecov
    - name: Test with pytest
      run: |
        python -m pytest --cov-report xml --cov=app --cov=poll --cov=formatters --cov=mattermost_api

    - name: Codecov Report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
        files: ./coverage.xml
        env_vars: OS,PYTHON
        flags: unittests
        fail_ci_if_error: true
        verbose: true
